export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
export const DECREASE_AMOUNT = 'DECREASE_AMOUNT';
export const FETCH_DATA = 'FETCH_DATA';
export const CALCULATE_TOTALS = 'CALCULATE_TOTALS';